engines:
  phpmd:
    enabled: true
    checks:
      CleanCode/ElseExpression:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Naming/LongVariable:
        enabled: false
      UnusedFormalParameter:
        enabled: false
      UnusedLocalVariable:
        enabled: false
      UnusedPrivateField:
        enabled: false
      UnusedPrivateMethod:
        enabled: false

    exclude_fingerprints:
    # The method src/MiniStruts::init() contains an exit expression.
    - fce18df2a012e7a27124db9a0cba9148
    - 57a63391d77425e3c2731e26b562982f
    
  duplication:
    enabled: true
    config:
      languages:
      - php

  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false

ratings:
  paths:
  - "**.php"

exclude_paths: []
