engines:
  phpmd:
    enabled: true
    checks:
      Controversial/Superglobals:
        enabled: false
    checks:
      UnusedLocalVariable:
        enabled: false

  duplication:
    enabled: true
    config:
      languages:
      - php

  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false

ratings:
  paths:
  - "**.php"

exclude_paths: []
