#!/bin/sh
#
# Set desired environment variables.
#

# By default PHP FastCGI processes exit after 500 requests.
# FcgidMaxRequestsPerProcess should be <= PHP_FCGI_MAX_REQUESTS.
export PHP_FCGI_MAX_REQUESTS=2000

# Enable to specify a custom php.ini (same as PHP CLI option: -c <path>|<file>).
#export PHPRC=./

# Replace with the path to your FastCGI-enabled PHP executable.
exec php-cgi "$@"
