#!/bin/sh
#

# PHP FastCGI processes exit after 500 requests by default.
export PHP_FCGI_MAX_REQUESTS=2000

# identical to: php -c <path>|<file>    Look for php.ini file in this directory
#export PHPRC=./

exec php-cgi $* 2>&1

