#!/bin/sh
#

# By default PHP FastCGI processes exit after 500 requests.
export PHP_FCGI_MAX_REQUESTS=5000

# custom php.ini, same as CLI option: -c <path>|<file>  (look for php.ini file in this directory)
#export PHPRC=./

exec php-cgi $* 2>&1
